name: Bug Report
description: File a bug report
title: "[Bug] CHANGE ME"
labels: [ "bug" ]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output, this will be used to help diagnose the issue. Please do not use any paste services, as they may expire and be deleted.
      placeholder: You can look into `.minecraft/logs` and find the `latest.log` and `rei.log`, you can paste them here.
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or additional log files by clicking this area to highlight it and then dragging files in.
  - type: markdown
    attributes:
      value: |
        Before submitting a bug report, please make sure that this issue has not already been reported. You can use the search feature to find existing issues.

        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: logs-confirm
    attributes:
      label: By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.
      options:
        - label: Yes, and I did not use any paste services other than GitHub Gists.
          required: true
  - type: checkboxes
    id: updates
    attributes:
      label: By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.
      options:
        - label: 'Yes'
          required: true
